### ISSUE TITLE
Unable to complete Exploring Your World:Nether Ores quest

### ISSUE THREAD

**Issue by jmcaffee** [CaiganMythFang/TheFerretBusinessIssues#10]
Even though I had Nether Coal, Nether Iron and Nether Sulfur Ores in my inventory, the quest wouldn't recognize them and complete.

I manually completed the quest myself with `bq_admin`.

**Comment by CaiganMythFang** [comment]
Do you have all three Nether Ores in your inventory at the same time when you hit Detect/Submit?

Currently there is an issue with non-consuming quests where all the items in a task must be in your inventory at the same time before it can be completed.

**Comment by jmcaffee** [comment]
That may have been the issue. I've already completed the task so really no way to check.
