### ISSUE TITLE
Recipe Book function error when recieving reward

### ISSUE THREAD

**Issue by Rh0k41** [CaiganMythFang/TheFerretBusinessIssues#100]
While testing Better questing, i set a recipe as a reward. When completing the quest, the game crashed. Attempting to re-enter the world causes a crash with the same error.
I noticed in the logs that it thinks I'm on a multiplayer server when I'm in singleplayer, is this normal?

Debug.log : https://gist.github.com/Rh0k41/668a2534c3efaaf536f368446710bf17

Latest.log : https://gist.github.com/Rh0k41/f5b70369a6da67cef3e20c2a61709d27

Crash Report : https://gist.github.com/Rh0k41/595df9bef5c85d9d420b4fdff2031c47

**Comment by CaiganMythFang** [comment]
Greetings!

This is the Ferret Business modpack github, not the Better Questing github. I cannot aid you in this issue, unfortunately. Sorry!

**Comment by Rh0k41** [comment]
> 
> 
> Greetings!
> 
> This is the Ferret Business modpack github, not the Better Questing github. I cannot aid you in this issue, unfortunately. Sorry!

Not sure how I made that mistake, sorry about that!
