### ISSUE TITLE
Quests does not load.

### ISSUE THREAD

**Issue by Magzar** [CaiganMythFang/TheFerretBusinessIssues#109]
Hi! I have wanted to play with a modpack that had this mod.
I opened the book and it loaded perfectly. But when I opened the questions menu, it did not load the questions.
My version is 3.5.271.
I also have a mod named BetterQuestingTriggerer. 1.0

**Comment by CaiganMythFang** [comment]
Greetings! This is not the github for Better Questing itself, and cannot assist with this issue. Sorry!
