### ISSUE TITLE
Server process kills itself

### ISSUE THREAD

**Issue by H4nSolo** [CaiganMythFang/TheFerretBusinessIssues#11]
Hi Guys, i need help with my server (The Ferret Business Server).

When i start my Server, he runs 1 - 2 Hours and crash without a error in the Console.
I start the Server with a Webinterface and i can look into the Gameconsole.
I can only see that the server process was killed.
No Errors, no Crash Logs or or other Messages about the killed Process :(

This is the only Message i can see only in my Webinterface:

```
OGP_HOME_000000055_startup_scr.sh: line 2:  1374 Killed                  java -Xms2G -Xmx25G -XX:MaxPermSize=256M -jar FerretBusinessServer.jar nogui
Server 'java -Xms2G -Xmx25G -XX:MaxPermSize=256M -jar FerretBusinessServer.jar nogui' crashed with exit code 0.  Respawning...
```

**Root Informations:**
Ubuntu 14.04 LTS
64GB Ram
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, 8 Core
Java 8

On Root we have 1 BungeeCord Proxy Server (1GB Ram), other 3 Bukkit Server (=> 35GB Ram) and a Voice Server ( Teamspeak). Sometimes we get a big Lag and it freezed the Root but this is a other Problem. My Big Problem is only That this Server ist permantly killed with no Errors or Something else...
I have run a Bevos Modpack Server before and he was stable....
My Trys:
- Disable the Backup Function [_Failed_]
- Editing Fastcraft settings [_Failed_]
- Editing Ram Settings [_Failed_]
- Reinstall the ModPack Server [_Failed_]
- Runs the Server with another optimiezed Java Parameters (Garbage collector) [_Failed_]

I have no more Ideas what i can try to fix that Problem :(

**Comment by CaiganMythFang** [comment]
After the next time it just closes without warning, could you upload the latest.log from the /logs/ directory and link it here?

**Comment by H4nSolo** [comment]
Ok, I've fixed the problem,
On root we had a memory leak.
Our other servers had reserved too much RAM, and when I started the Modpack servers last, Java killed the server because of too little remaining Ram after a certain time.

Please therefore consider the problem solved and give others advice on their Ram Reserve.

greetings H4nSolo

**Comment by CaiganMythFang** [comment]
Glad the problem was resolved easily!
