### ISSUE TITLE
questbook transmission

### ISSUE THREAD

**Issue by Higuys153** [CaiganMythFang/TheFerretBusinessIssues#111]
the transmission does not play and pressing click to play again does nothing

**Comment by CaiganMythFang** [comment]
Unfortunately, unable to recreate the issue on a fresh install. It might be some issue with your system.

If you want to listen to the sound file, you can hit the three dots in Curseforge in the pack menu, 

https://i.imgur.com/UZ397Me.png

hit Open Folder, and navigate to config/hqm/lore.ogg

**Comment by Higuys153** [comment]
not using curseforge will try to find it tho

**Comment by Higuys153** [comment]
found it
