### ISSUE TITLE
Fire damage

### ISSUE THREAD

**Issue by Chinthor** [CaiganMythFang/TheFerretBusinessIssues#12]
Don't know if this is partly or fully intended, but here is what I'm seeing. I'm trying to become fireproof. Walk through flames and swim in lava. When I morph a fireproof mob, I still take fire damage, but cannot be set on fire. Botania's pyroclast pendant and crimson pendant also do not protect from fire damage. Morph.cfg is set to give me all mob abilities except flight until I kill the wither. Is there a tweak somewhere else that prevents this from working?

**Comment by CaiganMythFang** [comment]
Testing it locally, the Pyroclast and Crimson pendants work properly, as well as testing with fireproof properties of the Blaze.

Pyroclast does not stop fire/lava damage, it merely puts you out when you are on fire. It will not stop damage from standing in a fire.

Crimson Pendant does stop damage from both standing in fire/lava and being on fire.

**Comment by Gamebuster19901** [comment]
I do not have this issue.
