### ISSUE TITLE
Cannot make Diamond Chip

### ISSUE THREAD

**Issue by bvierra** [CaiganMythFang/TheFerretBusinessIssues#13]
Issue: Cannot create Diamond Chips as the recipe for both this and Diamond Nugget are the same using shapeless crafting. This causes issues with: OpenComputers - Microchip (Tier 3) as it only will accept Diamond Chips and not Nuggets.

Possible Fixes:
- Change Diamond Chip and Diamond Nugget to be Shaped Crafting using different slots for diamonds
- Change Microchip (Tier 3) to use either nuggets or chips

**Comment by CaiganMythFang** [comment]
Fix is already in place for the next update. Will be able to craft Diamond Nuggets into Diamond Chips.

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.1.
