### ISSUE TITLE
Compacting Drawers Ore Dictionary Issue

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#16]
0.2.1 Gosh Heckie version update when setting up compacting drawers to hold ingots I am getting very odd crossovers. The few ingots I tried were Iron, Gold, Invar, Tin, and Aluminium. Iron gave me compressed crafting tables instead of nuggets. Invar gave me copper instead of nuggets. Much to my surprise aluminum gave me steel instead of nuggets. There is obviously some kind of cross conflict after the update that is causing compacting drawers to read the wrong ore dictionary IDs for nuggets.

**Comment by CaiganMythFang** [comment]
Reported this issue to the Compact Storage dev earlier today. Already have a fix in place for the next update.

If you are playing single player, you can download the updated file : https://minecraft.curseforge.com/projects/storage-drawers/files/2355230 . Download it to your /mods/ folder in your installation folder (There is another issue topic that explains how to find it)

Just disable the previous version by adding .disabled to the end of the file name (so it'd be .jar.disabled)

**Comment by KahnWolfe** [comment]
Or if you know how to manage it like I do, simply go into the modpack folder and completely remove the previous version of it and update it. I didn't figure it was something on your end as I haven't found many errors thus far with the pack. 

I appreciate the quick response. I am in Single Player and am doing testing of the pack for errors and the like so that my crew can Youtube and Twitch stream this hopefully after the new year. Appreciate that quick response to it and will let you know if I happen to find anything else along the way.

**Comment by CaiganMythFang** [comment]
0.2.2 Update is out and fixes this issue. Some non-common compacting recipes may no longer work. If you find any, please report them and they will be re-added for the next update.
