### ISSUE TITLE
Nether Ores

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#17]
All nether ores when mined, regardless of tool (no not using auto-smelt) are dropping ingots as if all Tinker's construct pickaxes, hammers, etc etc have auto-smelt on it. Have tried using a vanilla style Invar pickaxe as well, same results. This is quite a bit of issue for anyone who wants to mine in the nether for resources as it would mean silk touch tools would be required to grab even basic ores. 

A slight bit of further testing shows that silk touch will harvest them normally.

**Comment by CaiganMythFang** [comment]
Okay, confirmed issue with the latest version of Nether Ores, and there is no config option to change it, nor is there a mention of this change. The bug reports to their github have gone unaddressed as well.

I will downgrade Nether Ores to NetherOres-[1.7.10]2.3.1-22 for the next update. You can switch to that version of Nether Ores as well until then if you want, or spawn in a silk touch pickaxe just for nether ores for the time being.

**Comment by KahnWolfe** [comment]
Much appreciated, with redress the issue manually for now.

**Comment by DarkTechnician** [comment]
How can early adopters of changes (like me) get NetherOres-[1.7.10]2.3.1-22, which isn't available on the NetherOres download page?

**Comment by CaiganMythFang** [comment]
https://minecraft.curseforge.com/projects/netherores/files/2277488

The CurseForge files list usually has older versions of most mods, unless the mod authors remove them for various reasons (like InventoryTweaks removed every one before the latest 1.7 version)

**Comment by DarkTechnician** [comment]
Ah, there's why I didn't see it the first time.. I was looking for 2.3.2, not 2.3.1. You have in the changelog it listed as a change from 2.3.2B1 to 2.3.2.

**Comment by CaiganMythFang** [comment]
Oh, oops. That was a typo, my apologies!

**Comment by CaiganMythFang** [comment]
0.2.2 Update is out, which fixes this issue.
