### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by DarkTechnician** [CaiganMythFang/TheFerretBusinessIssues#20]
So.. I just opened a "Luck of the Dragon" Blind bag.. that Crashed the game.
'full'
http://pastebin.com/0nxiqG4z

'crashlog'
http://pastebin.com/Ac6R3fw7

**Comment by CaiganMythFang** [comment]
Second pastebin is marked private so I can't see it.

Corrected an issue with the Luck of the Dragon bag though, thanks!

**Comment by CaiganMythFang** [comment]
0.2.2 Update is out, fixes this issue.
