### ISSUE TITLE
Morphing into a Naga (Twilight forest) creates dozens of large, unkillable entities.

### ISSUE THREAD

**Issue by Gamebuster19901** [CaiganMythFang/TheFerretBusinessIssues#21]
![2016-12-22_18 59 46](https://cloud.githubusercontent.com/assets/7155747/21444198/3a171876-c879-11e6-8558-8dd7ce98edd5.png)

This can be fixed by disabling morph for the Naga boss.

**Comment by CaiganMythFang** [comment]
Marking as Needs Research since the next update is submitted but not live yet. Will be fixed in 0.2.3.

**Comment by Gamebuster19901** [comment]
Also, a correction, it's not when you morph into a naga, it's when you change to something else when you're a naga.

**Comment by KahnWolfe** [comment]
This is not exclusive to this pack as I was watching someone play another pack that had both morph and twilight forest. It seems to be an oddity between the two mods and not something directly related to this pack. Should be reported to both Morph and Twilight Forest mod teams.

**Comment by Gamebuster19901** [comment]
I would not bother a fellow mod author with bugs in long outdated versions of their mods. I know from experience that it's annoying. If it still exists in the latest versions of their mods, then report it.

**Comment by Gamebuster19901** [comment]
Has this been fixed? I believe Morph has a blacklist file to prevent the player from transforming into specific mobs.

**Comment by CaiganMythFang** [comment]
This has not been fixed yet but I will be trying to get it in properly in the next update.

**Comment by Gamebuster19901** [comment]
I have attached an updated config file to this comment which fixes the issue. Note that github will not allow me to upload a .cfg file to a comment, so I had to append .txt to the end. Rename the file and remove the .txt extension to use it.
[Morph.cfg.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/1608498/Morph.cfg.txt)

**Comment by Gamebuster19901** [comment]
Fixed in 7e2ae604977aff3cf06184d61ea431d9888bdefc (0.2.6)
