### ISSUE TITLE
I cant log into my world or i cant create a new world

### ISSUE THREAD

**Issue by KenaxCZ** [CaiganMythFang/TheFerretBusinessIssues#22]

**Comment by Ristellise** [comment]
log? anything???

**Comment by KenaxCZ** [comment]
no, loading world and nothing

**Comment by Ristellise** [comment]
i mean could you post your log(fml-latest) in gist.github.com ?

**Comment by KenaxCZ** [comment]
[fml-client-latest.zip](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/671766/fml-client-latest.zip)

**Comment by CaiganMythFang** [comment]
Your EnderStorage save data has become corrupted. 

If you try to load a world that has a corrupted EnderStorage save data, it will give a GZIP error, and your game will continue to give that error even when you try to make a new world.  The only way around it is to either restart THEN make a new world, or to delete the EnderStorage save data for the corrupted world.

In your world's save folder, delete the /EnderStorage/ folder, and relaunch the game. This link explains how to find your install folder : 
https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/1

Your world is saved in /minecraft/saves/(world name)

**Comment by KenaxCZ** [comment]
thx

**Comment by CaiganMythFang** [comment]
For search reference for others who may encounter this issue, the error in the logs is as follows : 
[13:30:53] [Server thread/ERROR] [FML/]: Caught exception from EnderStorage
java.lang.RuntimeException: java.util.zip.ZipException: Not in GZIP format
	at codechicken.enderstorage.api.EnderStorageManager.load(EnderStorageManager.java:108) ~[EnderStorageManager.class:?]
	at codechicken.enderstorage.api.EnderStorageManager.<init>(EnderStorageManager.java:79) ~[EnderStorageManager.class:?]
	at codechicken.enderstorage.api.EnderStorageManager.reloadManager(EnderStorageManager.java:139) ~[EnderStorageManager.class:?]

**Comment by KenaxCZ** [comment]
![yijt](https://cloud.githubusercontent.com/assets/24752095/21467555/5438d1c0-c9f2-11e6-96cb-b39ab4b91561.png)

**Comment by CaiganMythFang** [comment]
You'll need to revert to a backup in your minecraft/ftbutil-backups folder. You should be able to just replace the level.dat with one of your backups, but you might need to extract the entire backup instead.
