### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by KenaxCZ** [CaiganMythFang/TheFerretBusinessIssues#23]
![yijt](https://cloud.githubusercontent.com/assets/24752095/21467564/a63544ae-c9f2-11e6-9ec3-246bcf3bdaac.png)

**Comment by KenaxCZ** [comment]
when i click yes game crash

**Comment by CaiganMythFang** [comment]
You'll need to revert to a backup in your minecraft/ftbutil-backups folder. You should be able to just replace the level.dat with one of your backups, but you might need to extract the entire backup instead.

**Comment by KenaxCZ** [comment]
nice thx
