### ISSUE TITLE
Exchange Rewards unlocked

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#24]
Since the scoreboard system has been removed for using the chit system, it seems that as long as you have the coins you can simply just go right up the Tier tree and instantly unlock diamond exchange tokens as for some reason it isn't locking it behind related quests at the moment.

**Comment by CaiganMythFang** [comment]
Is this likewise for all three tracks or only shop rank?

**Comment by CaiganMythFang** [comment]
Nevermind, I was able to look through the database file and see what happened (and slightly misunderstood what you meant).
They somehow lost the prerequisite of the appropriate Shop Rank quest.

This'll be fixed next update.

**Comment by KahnWolfe** [comment]
I figured you would want to know, sorry for stating it the way I did, but yes. The pre-requisites got lost in the progression so you can just instantly unlock the highest tier of exchange rate without having first increased trader rank etc etc.
