### ISSUE TITLE
Mekanism Gas Tank missing Recipe

### ISSUE THREAD

**Issue by Broklyndatroll** [CaiganMythFang/TheFerretBusinessIssues#28]
Currently (0.2.1) NEI does not display any recipe for the Mekanism Basic Gas Tank (ID 1544:100). Using the standard recipe of 8 Osmium Ingots surrounding an Iron Dust also does not work.

I am currently playing The Ferret Business 0.2.1 modpack on the MineYourMind Network using their MYM Launcher. To the best of my knowledge the modpack/recipes have not been altered by MyM. 

So I'm curious if this recipe is missing for anyone else?

**Comment by Gamebuster19901** [comment]
The recipe still exists, it just doesn't show up in NEI. You are using the wrong recipe, it is this:

![2016-12-28_11 16 16](https://cloud.githubusercontent.com/assets/7155747/21526019/3933180e-ccef-11e6-8091-489d120c3c05.png)

I am running version 0.2.2, but I reinstalled Matter Overdrive, if anyone was wondering.

**Comment by Broklyndatroll** [comment]
Thank you, that worked. Oddly it still shows no recipe if I access it through NEI, only if I check it from my inventory, but that can be resolved server-side. The one in my NEI lists item ID 1544:100, while the one I was able to make using the recipe you provided lists as 1544, which is the likely issue.

Thanks again!
