### ISSUE TITLE
Bones of Dragons

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#30]
I have unlocked the penultimate research quest but can go no further with anything related to draconic evolution as the Bones of Dragons quest is missing entirely from the quest book. I did the reset for the 0.2.2 update and restarted all questing, however the quest bones of dragons does not appear at all. Even went so far as to take down the ender dragon in hopes it might trigger it with a vanilla related achievement, but no such luck. Also, have occasionally seen a flickering line glitch on the page which I noted that you had posted on the BQ forum as well. Was wondering what you can tell me in regards to this or if it is temporarily disabled due to the BQ issue.

**Comment by CaiganMythFang** [comment]
Hm, odd. Some of the quests set themselves to Hidden. I think this is a mistake on my part after the Hard Drive crash, and never got properly tested.

This is already fixed for the next update, but you can grab the quest database and update yourself if you don't want to wait for the next update : 
https://github.com/CaiganMythFang/TheFerretBusinessIssues/blob/develop/config/betterquesting/DefaultQuests.json

Place it into your config/betterquesting/ folder, and in game do /bq_admin default load

**Comment by Gamebuster19901** [comment]
Is the AE2 Questline complete? It doesn't say WIP, but there are some quests require "The ME Controller", but that quest is hidden and requires Bedrock to complete.
![image](https://cloud.githubusercontent.com/assets/7155747/21582497/77d243aa-d028-11e6-806a-d44a15bf466f.png)

![image](https://cloud.githubusercontent.com/assets/7155747/21582496/642bf710-d028-11e6-8c85-0c341cd44d2a.png)

**Comment by CaiganMythFang** [comment]
The first quest in the Crystalline Storage questline mentions that it is currently incomplete.

**Comment by CaiganMythFang** [comment]
Fixes in 0.2.5 and 0.2.6
