### ISSUE TITLE
Pickaxe of the Core trying to craft as Axe of the Stream

### ISSUE THREAD

**Issue by Aiidoneus** [CaiganMythFang/TheFerretBusinessIssues#32]
When trying to craft the Pickaxe of the Core on the infusion altar, it registers as trying to craft the Axe of the Stream. You can tell by looking at what the the aspects are on the altar when you activate it. This happens on the server I play on and in single player. Any suggestions on how to fix?

![](http://i.imgur.com/ausXcoA.png)

**Comment by CaiganMythFang** [comment]
Will add an Arcane Workbench recipe for this in the next update.

**Comment by bookerthegeek** [comment]
I might have a better fix, I'll post the script when I get home.

Love the pack and keep up the good work!
