### ISSUE TITLE
Fuzzycard bug

### ISSUE THREAD

**Issue by Jokki157** [CaiganMythFang/TheFerretBusinessIssues#33]
I made a mob ginder where the items looted goes into my ME network. To get rid off the bows i have a trash can with a Export buzz and Fuzzycard in it. But the Exportbuzz now takes other items with it. at the moment it is also taking my: Rubber, Raw plastic, Arrows and Clay.

**Comment by Gamebuster19901** [comment]
It might be possible that it's taking based on oreDictionary values, and this pack adds FMC which uses the oreDictionary.

**Comment by CaiganMythFang** [comment]
This sounds like its grabbing the OreDictionary value for items. All of those are the same ore dictionary for the FMC system.

Unfortunately, this is how Fuzzy Cards work, and not something I can fix easily (An overall update to the FMC system is planned, but unsure when it will happen)
