### ISSUE TITLE
Awakened Tools Quest Hidden

### ISSUE THREAD

**Issue by Aiidoneus** [CaiganMythFang/TheFerretBusinessIssues#34]
It looks like in the quest Awakened Tools in the Special Research questline is still hidden with your update on the DefaultQuest.json file you pushed out for it to be fixed in the next version. I assume it isn't suppose to be like this? Let me know please what is going on with it. =)

**Comment by CaiganMythFang** [comment]
It isn't, I apparently missed that quest.

The github file is updated now. https://github.com/CaiganMythFang/TheFerretBusinessIssues/blob/develop/config/betterquesting/DefaultQuests.json

**Comment by CaiganMythFang** [comment]
#30 Instructions for others on how to use this file.

**Comment by Aiidoneus** [comment]
Thank you very much! Keep up the great work.
