### ISSUE TITLE
tablet v2 is empty of quest ! maybe ME chest issue...

### ISSUE THREAD

**Issue by hectoskp** [CaiganMythFang/TheFerretBusinessIssues#35]
hello!
I report a thing that happened 2 times with my server,  version 0.2.0

i accidentally put my quest tablet v 2 in my ME Systeme from applied energistics, and when i try to use it,
and press the quest button, the quest list is empty and only purpose 2 actions:
done or edit. Just like the quest system was fully erased.
I try to give me an other tablet in creative but its the same problem...
is there a solution to reload the quest system?
where is the folder with the quest file in a server? and where can i download a proper quest file if necessary?
if i  backup my word and redownload the pack ,it could resolve the problem?

thanks for answer, excuse my english, im french.
you've done a great job with this mod pack i realy love it and dont want to play another!hectoskp

**Comment by CaiganMythFang** [comment]
The Quest Tablet v2 Item does not store any data on itself, it is only a trigger to open the Quest window.  Something else happened to your quest database.

For both Servers and Single Player worlds, the quest database is stored in the world folder. (for a server, that is usually /world/ ). The Default quest database, that new worlds copy from, is stored in /config/betterquesting/DefaultQuests.json

You can try /bq_admin default load to reload the Quest Database. If that doesn't work : 

1. Download https://github.com/CaiganMythFang/TheFerretBusinessIssues/blob/develop/config/betterquesting/DefaultQuests.json to /config/betterquesting/
2. Do /bq_admin default load in game
3. You'll most likely be in Edit mode again. Do /bq_admin edit to disable edit mode.

**Comment by hectoskp** [comment]
Excellent! i try /bq_admin default load and it works directly! and the progress of my quest tree was still in memory.
thank you very much for your fast solution!
Effectively ,there was a file named "malformed_questdatabase.json0.json" in the /world/ folder of the server.

thanks for your work, it's great!
hectoskp.
