### ISSUE TITLE
IE and NC recipe conflict

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#37]
The recipe for the IE sheet metal tanks (iron plate up down left right) is unfortunately the same as the cell crafting for NC's empty cells which basically means that you can not craft the tanks for IE without using an admin cheat mode to give them to yourself. Conflict is caused primarily due to the fact that you can use plates from either mod to make the other thanks to ore dictionary. Sadly, that cross mod compatibility then makes one recipe uncraftable.

**Comment by CaiganMythFang** [comment]
You can get around this by using a normal Crafting Table (not a tinkers
one) and using the arrow to the right of the output window. (No more recipe
conflicts mod). I'll note down this issue and fix it for the next update
though.

**Comment by CaiganMythFang** [comment]
Whoops, this looks to of been fixed last update (NC changed it to Tin Plating). Closing
