### ISSUE TITLE
BetterQuesting text formatting is messed up

### ISSUE THREAD

**Issue by Zaphara94** [CaiganMythFang/TheFerretBusinessIssues#38]
After the newest firmware update, things got a bit wonky. All of the quests reset (which was to be expected), however afterward, all of the formatting codes were no longer registering? I have some pictures with a few examples below:

![image](https://cloud.githubusercontent.com/assets/25303524/22212918/678ba358-e160-11e6-823f-8990f089c755.png)
![image](https://cloud.githubusercontent.com/assets/25303524/22212994/a20ba4e2-e160-11e6-8586-ef34fb33c972.png)

**Comment by CaiganMythFang** [comment]
This is a known issue that is hopefully fixed if we update Better Questing
to BQ 2 release in the next update.

**Comment by Zaphara94** [comment]
I have created a hotfix for this issue, it removes all formatting codes from the quest tablet. Just replace your current DefaultQuests.json file with [this one](https://www.dropbox.com/s/mxu2qdyu0c9tpbk/DefaultQuests.json?dl=1). Hopefully next update, we can have the pretty formatting back!
