### ISSUE TITLE
Quest Update Spam 2.0.10

### ISSUE THREAD

**Issue by jeffwmizell** [CaiganMythFang/TheFerretBusinessIssues#39]
With the update to 2.0.10 Quest Update is continuously splashed on the screen accompanied with the ding.

**Comment by Gamebuster19901** [comment]
That's because it's adding new quests. Eventually it will stop.

**Comment by CaiganMythFang** [comment]
This doesn't seem to happen for everyone, but I may have tracked down what caused it this time. Hopefully next update doesn't do this for you. (Apologies for super delayed reply to this)

**Comment by CaiganMythFang** [comment]
Cleaning up old open issues.

This seems to be not as much an issue in BQ2. Done my best to disable notifications where I can.
