### ISSUE TITLE
Thaumcraft Infusion Altar Recipe Aspect Mix-Match

### ISSUE THREAD

**Issue by Broklyndatroll** [CaiganMythFang/TheFerretBusinessIssues#40]
Bone Rod (1 Bone with an Entropy and Balanced Shard, 12 Perdito, 6 Praecantatio, & 6 Exanimis) is actually demanding 6 Tenebrae instead of the Exanimis and results in an Obsidian Rod

**Comment by Broklyndatroll** [comment]
Working through the Thaumcraft Quests at the moment, and just found that when performing the Infusion for the Sword of the Zephyr, it demands the Aspects from the Axe of the Stream (Arbor/Aqua) instead of the Aer/Motus/Potentia the Sword should require.  I know you found a similar issue with the Pickaxe of the Core -> Axe of the Stream so I find it pretty obvious this is part of the same underlying issue and am fairly certain as I progress I will find a few more mixed up recipes to report. 

Sadly this does mean that for any player without Creative Access, there is no way to complete many of the existing Thaumcraft quests.

**Comment by CaiganMythFang** [comment]
I'm going to go through all the infusion recipes closer to when the next update is ready, and see which ones are still broken. A few of these are only broken for some players, and it isn't clear what the underlying cause is still. One of the mods updated may fix it (but probably not). 

Apologies for the very long delay in this reply.

**Comment by AbsentAbigail** [comment]
While building all my Kami Stuff, I noticed that I can't seem to make the boots of the horizontal shield, I checked the recipe multiple times and asked a friend to double check, but the infusion matrix wouldn't do anything. Also replying to this, because I can't make my pickaxes of the core either.
