### ISSUE TITLE
better quest

### ISSUE THREAD

**Issue by M1nKsTeR** [CaiganMythFang/TheFerretBusinessIssues#42]
in multiplayer better quests doesnt complete starting quests how do i do the quests?

**Comment by CaiganMythFang** [comment]
Are you playing on a server set to offline mode? If not, you can complete the starting quests via the commands listed in [this thread.](https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/5)

**Comment by M1nKsTeR** [comment]
thanks everything is fixed so far if any bugs or glitches i will find ill be sure to report

**Comment by M1nKsTeR** [comment]
so far im enjoying this modpack with friend
