### ISSUE TITLE
Quest repeat

### ISSUE THREAD

**Issue by YouCanNotKnow** [CaiganMythFang/TheFerretBusinessIssues#44]
Im trying to make a modpack where there are trades and when you complete the quest it instantly renews so you can do it again. I change the "repeattime" in advanced settings on that quest to 0 and i tested it by completing it with the command. I looked back at the quest and the cooldown kept on counting down pass the negatives. Then i changed the "repeattime" to 10 to see if it would work at 10 seconds but it was at 0 then started counting down into negatives. How can i fix this?

**Comment by CaiganMythFang** [comment]
This I'm not sure, it's not really my mod, so I can't really help with that issue.
