### ISSUE TITLE
Server Stopping Automaticlly

### ISSUE THREAD

**Issue by Midori-Okane** [CaiganMythFang/TheFerretBusinessIssues#46]
https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/1083422/crash-2017-06-18_18.17.34-server.txtThe server will stop automatically by saying Server ERROR and then SERVER stopped , it auto resolved the first time but it happened again after loading up the server.

**Comment by Midori-Okane** [comment]
[crash-2017-06-18_18.17.34-server.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/1083422/crash-2017-06-18_18.17.34-server.txt)

**Comment by CaiganMythFang** [comment]
Greetings, sorry for not getting back to you quicker!

Something caused the Fluxed Crystal 2's seed data file got corrupted (this can happen rarely if the game or server crashe or is shut down improperly)

Instructions for fixing this issue can be found here : https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/4

**Comment by Midori-Okane** [comment]
Thank you so much! This fixed the issue and everything is running as normal.
