### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by Xlayton** [CaiganMythFang/TheFerretBusinessIssues#48]
I use beastnode to host, and Ive been trying to set up a server, but each time I do it gives me an error stating that I am missing core libraries. I have tried to re upload the libraries folder, but to no avail.

pastebin crash log:
[server help.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/1126864/server.help.txt)

**Comment by Ristellise** [comment]
ask beastnode for help :)

https://www.beastnode.com/portal/knowledgebase
