### ISSUE TITLE
Can't fit all textures Crash

### ISSUE THREAD

**Issue by AbsentAbigail** [CaiganMythFang/TheFerretBusinessIssues#49]
I've been playing this Modpack for a bit now and suddenly I get a java.lang.RuntimeException error, saying "Can't fit all textures, use lower resolution texture packs or remove mods." I don't think I changed anything since playing the last time and reinstalling didn't help either. (https://pastebin.com/jdTrrvFA)

I am not using a texture pack and I can't remove any mods, because I'm on a server.

**Comment by CaiganMythFang** [comment]
Try disabling Fast Craft, which is a client side mod and should be fine to disable even if you are playing on a server.

Also make sure your graphics drivers and Java is up to date, as I'm seeing similar reports pointing to these as being possible culprits.

**Comment by AbsentAbigail** [comment]
So I've started it again (without changing anything) and now it works (I tried it 3 times before and after reinstalling, but it didn't work), it seems to have magically fixed itself and I have no idea how. Thanks for the quick reply though!
