### ISSUE TITLE
No tasks

### ISSUE THREAD

**Issue by rishi-khiroya** [CaiganMythFang/TheFerretBusinessIssues#50]
When i try make a quest and click tasks nothing shows up 
![image](https://user-images.githubusercontent.com/29337613/32404261-8731f300-c144-11e7-8fd0-e53ee30f8dd1.png)

**Comment by CaiganMythFang** [comment]
This is not the GitHub for Better Questing help directly, only for issues specifically with The Ferret Business.

[Link to the Better Questing Github](https://github.com/Funwayguy/BetterQuesting/issues).
