### ISSUE TITLE
Mass-Quests crash by select

### ISSUE THREAD

**Issue by fullmetalxp24** [CaiganMythFang/TheFerretBusinessIssues#51]
Everytime, I try to activate the massproduction-quests, the local server crashes and sends me to the mp-server-change-page. Is this a common bug?

**Comment by fullmetalxp24** [comment]
and sadly I cannot send any log... my pc deletes everything, even when I'm fast enough to save it elsewhere...

**Comment by CaiganMythFang** [comment]
Is this on the latest version I just released (0.2.5)? 
And which mass production quests specifically? (there's a few that could be considered that) If its in the QUEST Tablet, hold Shift when hovering your mouse over the quest to get the number for me.

**Comment by CaiganMythFang** [comment]
Closing for now, reopen if issue is still in current release (0.2.5) please.

**Comment by Cyperangel** [comment]
I crash any time I try to submit quests 56 to 60 from the questbook. And there are no options in the RF submitter block, to choose which quest to fulfill. I will be happy to provide further info, if needed. And yes, it is the 0.2.5 version.

**Comment by CaiganMythFang** [comment]
Reopening issue since it seems a few of these quests are bugged.

Looking into it, it seems the RF Better Questing addon is not updated properly to handle latest BQ2 changes. 

I am going to to hide the RF Quests and possibly remove them all together at this point, unfortunately.

**Comment by CaiganMythFang** [comment]
RF Quests are hidden and will be removed (along with the BQ2 RF Addon mod) next version to fix these issues. BQ2 for 1.7 is no longer being updated.
