### ISSUE TITLE
Uncrafting Goods Crate using uncrafting table

### ISSUE THREAD

**Issue by ming0328ming** [CaiganMythFang/TheFerretBusinessIssues#52]
Basically what the title says, doing that gives you assess to basically any items

**Comment by CaiganMythFang** [comment]
Oh, looks like I should have added all the crates to the Uncrating blacklist. Will be added on my end and in the next update.

**Comment by Gamebuster19901** [comment]
There were more issues with the uncrafting table, specifically uncrafting contracts and mailed contracts. Fixed in #63

**Comment by CaiganMythFang** [comment]
Fixed (mostly) in 0.2.6. The blacklist sometimes breaks but is the best I can do for now.
