### ISSUE TITLE
Grand Prize Bag wrong item

### ISSUE THREAD

**Issue by ming0328ming** [CaiganMythFang/TheFerretBusinessIssues#54]
Grand Prize Bag gives you hearts (6809) instead of blindbags (6810)

**Comment by CaiganMythFang** [comment]
Whoops, missed this one being posted earlier, a newer one mentioned this issue as well.

**Comment by CaiganMythFang** [comment]
Duplicate of #59

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.6
