### ISSUE TITLE
Multiple-choice rewards not claimable

### ISSUE THREAD

**Issue by xXViralVirusXx** [CaiganMythFang/TheFerretBusinessIssues#56]
I looked through alot of google and didnt find any solutions to this. Is this a commonly seen one i have no idea about or is this new? Please help.

**Comment by CaiganMythFang** [comment]
Is it any quest doing this, or specific ones?  Are ALL the tasks complete (since some quests have 5+ task sets) Do you have the inventory space for all the items, as well?

**Comment by xXViralVirusXx** [comment]
Yes it starts happening up until the first reward on the Initial Research line that offers multiple choices. I believe the one with iron tools. And after that it continues on even on some single reward missions. Thank you for the quick reply as well.

**Comment by xXViralVirusXx** [comment]
It has stopped as of now, the exact issue was that the claim button was not lighting up therefore i could not click it. This may be a issue with it recognizing both tasks as complete? But it stopped, ill send a screenshot if it ever happens again.

**Comment by KahnWolfe** [comment]
I have seen this issue with the claim button bugging out on occasion as well. It seems less inclined to pop up and highlight like it should. It can usually be resolved by flipping arrows on a multiple component quest, or simply by closing and opening the quest book again. Basically it seems like it doesn't update or refresh after the submit button is pressed.

**Comment by CaiganMythFang** [comment]
Going to close this as Better Questing 2 is not getting updated for 1.7 anymore and something I cannot fix myself.
