### ISSUE TITLE
Sag Mill Ferret Researchology items

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#57]
I manually fixed the missing close tags in the sag mill recipe in order to get them working again as after all I need to process a great number of things to get the finances need to buy my draconic evolution items. However in doing automation I found a bug with the Sag Mill. The Researchology items such as rotted bones, fur tufts, so on and so forth will ONLY insert into a sag mill if there are 10 of them, OR if there is a remainder in there. Simply put, in order to auto process them with the sag mill after the quest book ones are complete you have to run them into a buffer and then use the pull function so that it will pull into the sag mill whenever there are 10 or more items, otherwise, it will lock out and refuse to insert the items into the sag mill and will not even let you manually click in less than 10 preventing you from efficiently automating processing of these materials.

**Comment by CaiganMythFang** [comment]
That's how the SAGMill works, so that it doesn't clog up with partial alloys in an automated system that uses one mill for multiple operations. 

I will hopefully have worked out a good workaround for the next update to bypass the SAGMill again if BQ2 hasn't fixed the issue.
