### ISSUE TITLE
Zombie, skeleton, and creeper head un-crafting. 

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#58]
The three heads listed there should likely be blacklisted for uncrafting as it is very broken. For example, uncrafting a zombie head will give you a wither skeleton skull, leather, rotten flesh, and an iron ingot. It is designed so if you are really desperate for a zombie head you can sacrifice a much more valuable wither skull, but with the uncrafting table it makes it entirely broken and far too easy to far wither skeleton skulls while also getting FAR too many rewards in addition to it.

**Comment by CaiganMythFang** [comment]
Will add those to the uncrafting blacklist

**Comment by CaiganMythFang** [comment]
Fixed (mostly) in 0.2.6. Occasionally the blacklist doesn't work, but is the best I can do for now.
