### ISSUE TITLE
Broken reward bag Sag Mill reward

### ISSUE THREAD

**Issue by KahnWolfe** [CaiganMythFang/TheFerretBusinessIssues#59]
Once you have completed all the quests for trader chits, shop tokens, etc, you are supposed to be able to run them through a sag mill to get the reward bags again. Sadly, for some reason the bag containing the reward bags says they are reward bags, but they are instead a broken black icon that is null and does not actually work.

**Comment by CaiganMythFang** [comment]
Hm strange, I'm going to figure the bag relies on item# (which is world dependent) vs mod:item designation. Will look into it.

**Comment by KahnWolfe** [comment]
I will check into it and see what I can get for you. Tis one of those oddities that I ran across where I get SO many trader tokens at this point that they pretty much go to waste. So was trying to do something with them. Opened up the bag and it said it was the reward bags. You hover over and it showed the IDs for the reward bags, but the icons were unclickable black blobs that did nothing. Like someone accidentally melted my bag down during shipping. XD

**Comment by KahnWolfe** [comment]
It seems the issue is indeed the item number (as after all I have a crew that wanted a couple of extra favorite mods added in to the pack so I am not straight ferret) The names and IDs are showing up right, but the item is showing as Gendustry honey comb. 
![2018-01-09_10 13 07](https://user-images.githubusercontent.com/24517624/34730930-667cb832-f526-11e7-93cc-62886889a774.png)

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.6
