### ISSUE TITLE
THAUMCRAFT ISSUES

### ISSUE THREAD

**Issue by CaiganMythFang** [CaiganMythFang/TheFerretBusinessIssues#6]
Currently, Thaumcraft has a few issues : 
## QUESTLINE TASK ISSUE

The Thaumcraft questline requires all the items in a task to be in the inventory before it can be completed, causing many tasks to require double the resources.

This will be fixed next update.
## INFUSIONS BUGGED

Some of the infusions have been reported not working. The infusion can be set up correctly, with all correct ingredients, but never start when activated. There are also reports of some items giving the wrong item. 

These need to be tested and confirmed not working, and a workaround implemented.
- [x] Transmutative Rod
  - [x] Tested
  - [x] New Recipe Created?
- [x] Thaumic Restorer
  - [x] Tested
  - [x] New Recipe Created?
- [x] Ichorium Axe (giving Ichorium Pick instead)
  - [x] Tested
  - [x] New Recipe Created?

**Comment by TheBlueTroll** [comment]
Can confirm, transmutative rod not infusable
![transrod](https://cloud.githubusercontent.com/assets/9428136/19076705/3d7974f2-8a8d-11e6-8126-9c105e397a86.png)

**Comment by CaiganMythFang** [comment]
Okay, the Thaumic Restorer and Transmutative Rod recipes work...sometimes. I've tried it multiple times with new altars and new saves, and sometimes it works, sometimes it doesn't.

As for the Ichorium Axe, it does do the Ichorium Sword recipe instead.

All three items will have Arcane Workbench equivalents added .

**Comment by CaiganMythFang** [comment]
Here are the updated Minetweaker scripts to add the Acrcane Workbench recipes : 

https://drive.google.com/file/d/0B7jvvxp1wXVVWDRMRnNzVnpEUnM/view?usp=sharing

Place them /minecraft/scripts/ folder. Refer to the Common Issues and Instructions issue for instructions on locating your install folder.
