### ISSUE TITLE
Can't bag coins.

### ISSUE THREAD

**Issue by CassandraRC7** [CaiganMythFang/TheFerretBusinessIssues#60]
The 'Bagging up Coins' quest is one-time, and the SAG mill does not accept the 50 coins to bag them.

**Comment by CaiganMythFang** [comment]
Currently, SAGMill turn-ins for Ferret Business stuff is broken. It is already fixed on my end and will be in the next update.

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.6
