### ISSUE TITLE
Sagmill Recipes missing for crates

### ISSUE THREAD

**Issue by Pando1991** [CaiganMythFang/TheFerretBusinessIssues#61]
Hi there First off just wanted to say im really loving this pack, i played ffor a brief time when it was first released and came back recently to check out the progress,
Great Work so far :)
im playing on the most updated version of the pack from the twitch client and im supposed to be able to hand in crates via the sagmill but non of them can even be inserted in to the mill,
i am still able to create vouchers with it and some other items, but cant hand in crates :(

**Comment by CaiganMythFang** [comment]
This is a known issue with the current version. A new update is in the works that fixex this and a bunch of other issues. Don't have an ETA yet due to real life work and projects taking precedence but it should be sometime in February!

**Comment by Pando1991** [comment]
Ok no problem, thank you very much for the speedy response, i hope all goes well with the pack as im loving so far and hope your real life work goes well too :P 
thanks again

**Comment by CaiganMythFang** [comment]
Fixed in 0.2.6.
