### ISSUE TITLE
Quest not Notifying when Complete

### ISSUE THREAD

**Issue by Nashonic** [CaiganMythFang/TheFerretBusinessIssues#62]
Hello, i currently made a quest book full of quests. I went into a single player world and once i would retrieve the materials needed for a quest it doesn't notify me like it does in project ozone lite. i have to click detect myself then select the rewards or claim reward. In project ozone lite you dont have to detect every time. It auto detects. Why is mine not auto detecting

**Comment by CaiganMythFang** [comment]
Do you mean in Ferret Business or a pack you made yourself?

**Comment by Nashonic** [comment]
Oh sorry about this, i thought this was a thread for betterquesting itself. I quickly wrote this up before i left for work. Its in a pack i created for a couple friends.

**Comment by Nashonic** [comment]
I found the correct github for better questing, and funway has answered my questions.

Thank you.

**Comment by CaiganMythFang** [comment]
No problem, good luck!
