### ISSUE TITLE
Unable to load world once logged off

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#64]
So i made a new world and played for a bit and i had to close it out for a little while but when i launched it back up and tried to load the world i got sent back to the main menu and it nothing would happen. I am stuck in that loop

**Comment by CaiganMythFang** [comment]
See if you can get me console logs from after you try to connect.

The usual culprit in this instance is Morph. Try disabling that and loading the world again.

**Comment by Snowyvaan** [comment]
how do you get the console logs? this is the first time I've done troubleshooting like this.

**Comment by Snowyvaan** [comment]
it doesnt do it every time tho so i am thinking it happens when my pc locks up and it takes longer than usual to load so it goes into an invalid state or something like that

**Comment by CaiganMythFang** [comment]
Which launcher are you using? FTB or Twitch?

As well, how much memory do you have allocated in the launcher?

**Comment by Snowyvaan** [comment]
FTB and 4 gigs out of my 8 total

**Comment by CaiganMythFang** [comment]
You have enough memory allocated, that's good.

In the FTB Launcher, in the Options menu, there is "Show Console?", make sure it is checked. It'll keep a console open while the game is running.

Try logging into the world, and then when it boots you back out, go to that console window and hit Upload Log. It'll upload the log to the FTB site and open the URL for you, which can just paste here for me. =)

**Comment by Snowyvaan** [comment]
well it hasnt done it in a long time but i found out another bug or problem
when the quest book is open and i try to scroll down on the differnt quests it forces me back up and just jitters so i cant see the bottom of the quest sections

**Comment by CaiganMythFang** [comment]
Fix noted in #65
