### ISSUE TITLE
Quest book slider

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#65]
new thread new problem but when i try to use the slider bar in the quest book it just shoves me back up to the top of it so i cant go to the bottom  part of it to see those quests

**Comment by CaiganMythFang** [comment]
In 0.2.5 (or 0.2.6 which I think is now available in the launcher), have
you run the Firmware Update quest on the first quest page? (the quest with
the yellow ! Icon)

**Comment by Snowyvaan** [comment]
launcher still says 0.2.5 for me but i think so

**Comment by CaiganMythFang** [comment]
The quest book quests do not auto update when a new version of the pack is
downloaded. Firmware Update quest is required, or doing /bq_admin default
load.

Either way though, did you complete (or try to) any of the RF quests in the
Large Scale Orders section?

**Comment by Snowyvaan** [comment]
the small amount ones yes

**Comment by Snowyvaan** [comment]
also i did the firmware quest but its still giving me the same problem that i cant scroll down

**Comment by CaiganMythFang** [comment]
You'll need to reset the RF quests to fix that issue. I'll let you know
what commands to run in about an hour when I  get home

**Comment by CaiganMythFang** [comment]
Okay, do the following commands, replacing username with your own in game name, and # with the quest ID number : 
/bq_admin reset # username

The quest numbers for the RF quests : 
Tiny : 60, 483, 489
Small : 56, 484, 491
Medium : 58, 486, 492
Large : 57, 487, 493
Giant : 59, 488, 546

EXAMPLE : /bq_admin reset 60 snowyvaan

**Comment by CaiganMythFang** [comment]
Closing for now, if the issue persists let me know.
