### ISSUE TITLE
Unable to update pack

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#66]
so i have tried 3 times to update and each time its given me the "error updating pack" message each time is there a bug in it or just me? also dropping link to paste bin of console 
https://pastebin.com/bgx5uxtS

**Comment by CaiganMythFang** [comment]
It's a bug on FTB's side currently, the Third Party Pack team has already been notified.

For now, the Twitch launcher version still works until the FTB launcher one is fixed.

**Comment by Snowyvaan** [comment]
oh boy lets see if i remember my twich login info

**Comment by Snowyvaan** [comment]
ok now twitch is saying i cant even install the pack. it just error while downloading cuz of timeout when nothing is wrong with my wifi (at least as far as i know this could just be a problem on my end but thought it was worth noting)

**Comment by Snowyvaan** [comment]
ok it appears to be the same mods it fails to download next time it happens i will get the names of them

**Comment by Snowyvaan** [comment]
![image](https://user-images.githubusercontent.com/36470435/36713832-129abe76-1b55-11e8-8fb2-dcd33535db48.png)
ok so same mod but it shows up twice and its every time

**Comment by Snowyvaan** [comment]
oh feedthebeast didnt error when updating it so thats fixed

**Comment by CaiganMythFang** [comment]
I'll check on if  the twitch version has broken when I can. A few folks
had reported it worked before so hopefully it's a simple fix on their end.

**Comment by CaiganMythFang** [comment]
Downloaded and ran pack fine on my end via Twitch. Timeout might be an issue that was only around that time, or some connection between you and Twitch.

FTB launcher version is fixed now though =)

**Comment by Snowyvaan** [comment]
sorry about the delay in getting back to this had some irl stuff pop up. I retried the twitch version and it was just my bad connection giving me the timeouts so gonna be starting over on twitch then. (also I dont know if there is a discord or something to just talk about the pack and stuff but that aint important)

**Comment by CaiganMythFang** [comment]
https://discord.gg/0sSRBJTxlwED9pTZ Is the discord link for this and other packs of mine =) It's not too active since its between updates for everything right now.
