### ISSUE TITLE
Fatal error with the uncrafting table

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#67]
so with the uncrafting table it shows the arrow to let you chose from differnt recipes to uncraft the item into and when i click through that it gives me the "fatal error" messages an closes my world

**Comment by Gamebuster19901** [comment]
I haven't had this issue. What item are you uncrafting and can you post the error?

**Comment by Snowyvaan** [comment]
i can grab the logs if it happens again and well its any item with more than one recipe to make it. it happened first with iron ingot to get the grimore of gaia item cuz i like have it around it and then again with seeing how a diamond was made with it

**Comment by CaiganMythFang** [comment]
Okay I can repeat this sometimes, it doesn't crash all the time though.

It looks to be when it tries to find a recipe, component, etc with AE2's recipe handler and its not liking something with it.

Will research this more.

**Comment by ghost** [comment]
Hello I have the same issue.
I was trying to uncraft Emerald into Emerald Nuggets as I clicked the arrow my game closed i the same way Snowyvaan reported.
