### ISSUE TITLE
Ordo Imbued fire makes free money.

### ISSUE THREAD

**Issue by interlamer** [CaiganMythFang/TheFerretBusinessIssues#69]
There's a pretty broken behavior with TT ordo imbued fire and compressed/double compressed blocks. It allows for about x27 ore multiplication. Steps to replicate: 
Get a big honkin' pile of metal blocks, light them up (w/ ordo imbued fire), ???, profit.
[screenshot](http://i68.tinypic.com/312d89g.png)

**Comment by CaiganMythFang** [comment]
I don't think theres much I can do to prevent this interaction given how Ordo Imbued Fire (or any of the imbued fires) works. Considering options, it might be one that needs to be removed/disabled. Will look into options for it.

**Comment by interlamer** [comment]
Ok, although it would be sad to have ordo fire disabled. I like to use it to x3 ores until I can x5 them via Mekanism.

**Comment by CaiganMythFang** [comment]
Unfortunately, I'm going to disable Imbued Fire overall, due to multiple bugs and issues with it I cannot control (spread speed, Perdito Imbued working reliably, which blocks it works with, etc). I wish I could leave it in as its a fun crazy mechanic, its just a bit too much.
