### ISSUE TITLE
Repeatable Quests continue to ding after completion.

### ISSUE THREAD

**Issue by Dhrekkin** [CaiganMythFang/TheFerretBusinessIssues#71]
Specific situation.  Two person group in a team, have a quest with a single task for mob hunting zombies, a reward that is set to choose from three items and an xp reward, the repeat timer is set to 600, the rewards are shared (every member of the team can pick one) and autoclaim is not selected.

Once it starts to ding that you've completed the quest it keeps going for about half an hour or so
Restarting the server does not correct it, nor does having everyone log in and out.  Deleting the quest while it is dinging does nothing, nor does setting the quest to be unrepeatable while it is going off.

**Comment by CaiganMythFang** [comment]
Sorry for the much delayed response. This is not the github for Better Questing itself, its specifically for The Ferret Business modpack. 

Hope you find a solution to your issues!
