### ISSUE TITLE
Not Enough Items Glitch

### ISSUE THREAD

**Issue by PFruitcake** [CaiganMythFang/TheFerretBusinessIssues#72]
The glitch lets you only see some random items which totals to 11 pages.

**Comment by CaiganMythFang** [comment]
That's an odd glitch. Could you give me any more information?

Any mods added, removed, configs changed?

Right click the black box under your inventory to clear it of any accidental spaces or other letters to see if that helps.

**Comment by CaiganMythFang** [comment]
Closing for now, let me know if this is still an issue.
