### ISSUE TITLE
Crashing upon launch

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#74]
here we are again it seems not even a day of being back and I break something I just installed it and tossed in the correct version of optifine for 1.7.10 the version twitch says the game is at and it crashes. here is the crash log

https://pastebin.com/3GZmjPw8

**Comment by CaiganMythFang** [comment]
Optifine has issues with this modpack, and it is suggested not to use it. Sorry!

**Comment by Snowyvaan** [comment]
its cool just a default for me to add it to max my fps since my laptop aint the spring chicken it used to be
