### ISSUE TITLE
Unable to load world

### ISSUE THREAD

**Issue by Snowyvaan** [CaiganMythFang/TheFerretBusinessIssues#75]
back again and I'm pretty sure I've given you this problem before but I couldnt find it before so just remaking this but I tried to load up a world I just played on a few hours ago and it says loading world but the flicks to the main menu and just stays there.
 hoping this isnt a dead pack

**Comment by CaiganMythFang** [comment]
Not a dead pack, just a very busy modpack dev right now =)

You did report this [here.](https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/64)

Was trying to get console logs from you so I could figure out the problem, but you said it had mostly stopped. 

If you could get me those console logs when it happens I can try to sort out what is causing the issue.

**Comment by Snowyvaan** [comment]
how do I get the console logs from it?

**Comment by Snowyvaan** [comment]
i think this is the log i dunno

https://pastebin.com/4MePqhEN

**Comment by CaiganMythFang** [comment]
Hmm that's a good chunk of it. I don't see where you are disconnecting back to the main menu.

I do see the Snooper is active, disable that as it spams the console and can slow down your game.

Options > Snooper Settings. 

----
For the full log, for when you've tried loading the world and get dropped (reposting this from other thread) : 

In the FTB Launcher, in the Options menu, there is "Show Console?", make sure it is checked. It'll keep a console open while the game is running.

Try logging into the world, and then when it boots you back out, go to that console window and hit Upload Log. It'll upload the log to the FTB site and open the URL for you, which can just paste here for me. =)

**Comment by Snowyvaan** [comment]
I am not using ftb I am using twitch

**Comment by Snowyvaan** [comment]
so not sure if its the same thing or not

**Comment by CaiganMythFang** [comment]
In Twitch client, when you have the pack selected, there is a [...] button in the upper right.  Click it, then Open Folder. This should open the install location for the modpack.

In the Logs folder, send me the latest.log

**Comment by Snowyvaan** [comment]
[2018-09-30-1.log.gz](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/2447410/2018-09-30-1.log.gz)
this should be it

**Comment by Gamebuster19901** [comment]
The integrated server is stopping before the client is able to connect to it. Sometimes the server can crash without printing the error to latest.log.

Here are some directions to get the server's crash log:

1. In the twitch client, click [...], then [Open Folder]
2. There should be a folder called [crash-reports], open it. If there is no folder called crash-reports, then the server is not crashing.
3. Upload the latest crash report that has "-server" on the end. The dates are in YYYY-MM-DD format. If there is no report that has "-server" on the end, then the server is not crashing.

I also do see that a sounds.json is malformed, but that shouldn't cause the server to stop.

**Comment by Snowyvaan** [comment]
there is nothing that matches the date on the latest log the one where it didnt load the world

**Comment by CaiganMythFang** [comment]
Hm, yeah, the only 'warnings' or whatnot are the sounds.json, and that isn't causing the crashes (as its a normal 'warning' for the pack, from one of the mods as far as I can tell).

A few things to try I guess : disable fastcraft and morph.

Would you be able to upload the world somewhere, google drive or drop box or something, for me to examine? I'm pretty sure it isn't the world itself, but I want to rule it out.

Aside from that, the only things I can think to try, since the logs aren't providing errors, is to make a backup of your world, then disable a few mods, load the world, and see if it keeps crashing out. If it does, disable a few more.

**Comment by Snowyvaan** [comment]
Disableing them is removing them from the mods folder right? I've never had this problem in other modpacks so I am a bit in the dark here and I think I have dropbox I'll have to double check

**Comment by CaiganMythFang** [comment]
In twitch, in the same menu you hit Open Folder, you can hit Profile
Options (I believe is the option name) to change some specific options.

One of them is a check box to Unlock the pack for modification. This
enables buttons in the mod list that disable/enable mods easily.

This issue is very odd and I'm not sure what's going on. Sorry. =(

**Comment by Snowyvaan** [comment]
you have no reason to be sorry that is why there is this section for the odd cases. I mean it might just be this old laptop I am using

**Comment by Snowyvaan** [comment]
okay its unlocked and the mods disabled 

also here is world dont mind the bad building skills 
https://www.dropbox.com/s/4xu0h2qgu9e3y8z/back%20in%20the%20saddle%20-%20Copy.rar?dl=0

**Comment by Snowyvaan** [comment]
> Hm, yeah, the only 'warnings' or whatnot are the sounds.json, and that isn't causing the crashes (as its a normal 'warning' for the pack, from one of the mods as far as I can tell).
> 
> A few things to try I guess : disable fastcraft and morph.
> 
> Would you be able to upload the world somewhere, google drive or drop box or something, for me to examine? I'm pretty sure it isn't the world itself, but I want to rule it out.
> 
> Aside from that, the only things I can think to try, since the logs aren't providing errors, is to make a backup of your world, then disable a few mods, load the world, and see if it keeps crashing out. If it does, disable a few more.

yeah without fastcraft I cant play the game my pc aint the spring chicken it used to be and that was giving me at least stable fps so with every visual setting at low or off i lag on the menu without a world even loaded so I need to have fastcraft

**Comment by NaosRequiem** [comment]
[latest.log](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/3245080/latest.log)

So I'm having the same issue. It doesn't even get to the "Configuring World" part. as soon as i hit "create New World" it freezes on the background screen and doesn't give me a crash report. I get a report file, but the file is empty. I have this log though, if that helps any? I'm going to try disabling Snooper next, to see if that fixes it and will update accordingly, whether it does fix the issue or doesn't.
