### ISSUE TITLE
Not enough items missing

### ISSUE THREAD

**Issue by FrostTheDragon** [CaiganMythFang/TheFerretBusinessIssues#76]
not enough items isn't on the side but the mod is active, literally nothing about it shows up 
![mod bug](https://user-images.githubusercontent.com/44588604/47679962-f1539280-db9b-11e8-9649-aa0d3b591d8e.png)

**Comment by CaiganMythFang** [comment]
Hit o on the keyboard, that turns the nei overlay on and off

**Comment by FrostTheDragon** [comment]
thank you!!
