### ISSUE TITLE
My game is crashes sometime when i'm teleporting in hell or from hell

### ISSUE THREAD

**Issue by KontranRUS** [CaiganMythFang/TheFerretBusinessIssues#77]
This is a couple of my crash-reports: 
1. https://i.imgur.com/2vBeFHS.png
2. https://i.imgur.com/MSwb7Jh.png
3. https://i.imgur.com/iMkJiep.png

This started going on more often when I'm built big me system with autocrafting.

**Comment by CaiganMythFang** [comment]
The first is an issue with BQ2 that happens rarely, and will not be fixed for 1.7.10 unfortunately. 

The other two are occasional bugs with applied energistics/AE2stuff, which are possibly fixed with the last update to AE2stuff 1.7.10.
