### ISSUE TITLE
Error: Invalid blind bag contents (FB Survey Rewards)

### ISSUE THREAD

**Issue by Yggdrasil128** [CaiganMythFang/TheFerretBusinessIssues#78]
Hello,
I got a `Ferret Business Survey Rewards` bag from a Legendary Blind Bag, and when I tried to open that, it showed this error:

```
Invalid blind bag contents: MineFactoryReloaded:machine:1:1:3,{storedStack:{id:3s,Count:1b,Damage:0s},RepairCost:2,display:{Name:"Dirt Storage Unit"},storedQuantity:100000,locked:0b}
Uh oh, this Ferret Business Survey Rewards seems to be defective. Better report it to the company! (Please report this to Caigan on the FTB Forums or his Player.me)
You opened a Ferret Business Survey Rewards and got 1 x [Ring of Binding]!
```
It told me to report it, so here you go :D
If you need a full log, etc., let me know.

I'm playing on pack version `0.2.6`, but I added the mod `OpenPeripheralIntegration-1.7.10-0.6` and made a couple small config changes to AgriCraft and FTBU, none of which, I think, could have caused this error.

BTW, thanks for making this awesome pack, I really love it :D

**Comment by Yggdrasil128** [comment]
Also, the `Grand Prize Bag` seems to have issues:
```
Invalid blind bag contents: GoodyBags:ItemGoodyBag:0
Uh oh, this Grand Prize Bag seems to be defective. Better report it to the company! (Please report this to Caigan on the FTB Forums or his Player.me)
You opened a Grand Prize Bag and got 1 x [Grand Prize Bag]!
```

I received that Grand Prize Bag by SAG-milling a 4096 job chip.

**Comment by CaiganMythFang** [comment]
Whoops, I meant to reply to this earlier!

I found the issue (as well as two more broken items in the Survey Reward bag.

I've fixed those issues and the Grand Prize Bag issue.

Thanks for reporting them!
