### ISSUE TITLE
completing non existant quests

### ISSUE THREAD

**Issue by SevenChords** [CaiganMythFang/TheFerretBusinessIssues#80]
I noticed a pretty strange issue: evrything seems to work fine, except i get a quest completed notification/popup on screen for a quest that is not in my questbook, the quests that are in the questbook work fine, but it seems to have multiple hidden quests that i somehow completed but still can't see in the questbook.

**Comment by CaiganMythFang** [comment]
Are they popping up with an icon of a Nether Star, or the name New Quest or similar?

If you can remember, or more pop up, let me know the names. I've cleaned up most of the quests that were doing that, but there might be a few I missed.

**Comment by SevenChords** [comment]
it seems most of them were part of the techguns mod, like "kill bandits", some basic quests like "the beginning" with a stone as icon, no nether star and almost all of them had pretty descriptive names, could be an issue of the modpack though, will contact the creator of the pack as well (towncraft modpack version 2.53)

**Comment by CaiganMythFang** [comment]
Oh. Uh, this isn't the github for that modpack, this is the github for The Ferret Business modpack. 

Their github is, I think, [here](https://github.com/ProsperCraft/towncraft/issues)

Hope you get your issue resolved! =)
