### ISSUE TITLE
dense diamond ore has double FMC value

### ISSUE THREAD

**Issue by Cyperangel** [CaiganMythFang/TheFerretBusinessIssues#85]
![densediamondore](https://user-images.githubusercontent.com/36072900/59085195-1fe9d680-88fe-11e9-9cea-4fdbca0875b6.jpg)
AS can be seen by this cropped image, the dense diamond ore is sporting two different FMC values.

**Comment by DarkTechnician** [comment]
Already fixed as of [https://github.com/CaiganMythFang/TheFerretBusinessIssues/commit/01c08619b80a12cff52175b1daac394c02842e4f](url)
