### ISSUE TITLE
game crash on start up

### ISSUE THREAD

**Issue by silksight** [CaiganMythFang/TheFerretBusinessIssues#86]
[game crash.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/3360621/game.crash.txt)

**Comment by CaiganMythFang** [comment]
Hello!

I think you have posted to the wrong github for your issue.

This is the GitHub for The Ferret Business (1.7.10) pack.

What pack are you playing? I can possibly point you in the correct direction.

**Comment by silksight** [comment]
sorry, im  trying to play forever stranded
