### ISSUE TITLE
Issue with downloading modpack

### ISSUE THREAD

**Issue by owoj** [CaiganMythFang/TheFerretBusinessIssues#88]
When trying to download the modpack, i get an error as soon as the 'Unzipping Modpack' message appears while loading.

I spoke to Twitch people about this and at some point they stopped emailing me back about this issue, leaving it unsolved.
This is the error message i receive
`Failed to unzip [NON ZERO EXIT CODE (50)]. The disk is (or was) full during extraction. error: cannot create /var/folders/jd/1pr2l1412wqb6mj1jg2fq7cm0000gn/T/Curse Client/1E2EF62F2D5147FF956D90BA72D5C95F/8/overrides/config/books/caigan, -?fAssistant Disposable Defense Kit Illegal byte sequence error: cannot create /var/folders/jd/1pr2l1412wqb6mj1jg2fq7cm0000gn/T/Curse Client/1E2EF62F2D5147FF956D90BA72D5C95F/8/overrides/config/books/caigan, -?fAssistant Disposable Defense Kit.dat Illegal byte sequence`

While writing this I just found an email with Twitch saying "Unfortunately, this pack has not been updated since Wednesday, February 2018 and it appears to be out of date now.

Modpacks Authors are solely responsible for keeping their Packs up date and fully functional."

Not sure what I could do to make this work for me.

**Comment by CaiganMythFang** [comment]
I just cleared and redownloaded the pack on my Twitch to test and it works.

By the error message, it sounds like the drive you have Twitch on is full.

`The disk is (or was) full during extraction.`

Double check that you have enough space on your drives(both the drive you have curse on, and your main windows drive if they are different) and let me know if the pack still errors when you try to download it.

If it does, I'll look into it further.

**Comment by owoj** [comment]
The thing is I’m using a mac, so from my experience, not sure how i’d be able to have more than one disk on it, but whatever i have the location of the folder (currently on desktop for some reason), my mac has 100+gb of storage available right now, so not sure what i could do about that

**Comment by owoj** [comment]
also may i note, that when i was dealing with this problem towards Twitch, this was september/october 2018, and since then i haven’t touched upon this situation, so coming back almost a year, and i’m still having the same problem, as i thought that maybe after time it might fix itself

**Comment by CaiganMythFang** [comment]
I...am not sure that this is a problem I can fix on my end, since that error isn't pointing to the modpack download itself I think. But lets see what we can do...

Can you try downloading the modpack zip from the twitch website (click Download instead of Install [here](https://www.curseforge.com/minecraft/modpacks/the-ferret-business/files/2533471) ). 

Then in Twitch, do Create Custom Profile and click Import (small text under the title) and select the modpack zip.

If that doesn't work, you can import [this archive](https://drive.google.com/file/d/1nHjbc4Qerjr5f-jkJF0AcJ02zVAZDmtd/view) into MultiMC instead (this will not work with twitch!)

**Comment by owoj** [comment]
I tried doing both of those, also wasnt sure if i by accident switched the files that i was supposed to use in their respective area of use so i tried each on both and none of those worked :(

**Comment by CaiganMythFang** [comment]
Whoops, I linked the server pack on accident

Try importing this file in MultiMC : https://drive.google.com/file/d/1vozugewms_4eXjQQiVodl1be18pMPZeo/view?usp=sharing
