### ISSUE TITLE
Drawer drain

### ISSUE THREAD

**Issue by PeanutGallery1971** [CaiganMythFang/TheFerretBusinessIssues#89]
I didn't verify if it happens with all drawers, but if you put a drawer over a hopper loaded with 4 slots of one thing (i.e. redwood roots), then add a fourth (i.e. Birch logs), any items over 1 stack of the first type "drain" away, lost to the void forever.  I was using this to load an alloy smelter to automate making charcoal.  I added a small stack of Birch logs to the hopper and noticed the roots were dwindling.  lol, I went from 800+ roots down to 64!  Once it hit 64, it stopped dropping.  Any roots added after also disappeared.

**Comment by CaiganMythFang** [comment]
Confirmed this issue on my end. A very strange bug. 

I see it's been reported to the Storage Drawer's github, but development of the 1.7.10 version of Storage Drawers ended years ago so it is unlikely this bug will be fixed on their end.
