### ISSUE TITLE
1/2 a Q.U.E.S.T. tablet

### ISSUE THREAD

**Issue by Haronobu** [CaiganMythFang/TheFerretBusinessIssues#9]
I am playing on prospercraft servers and no matter what i do i only get 12 questlines in the tablet (ending with automation station). i am using ftb launcher  and the pack version is 2.0, 5 gigs set aside for minecraft and running java 8 update 101  64 bit. Also fastcraft 1.23 is enabled.
  I have tried force update, uninstalled completely, rebooted and reinstalled, Started new SP game, completed entire initial research page and get the same thing ( on the server they said  to do an SP game and get the tablet updated so it will work in multi). Google had nothing so i assume this isn't common (just my luck). tech on discord says " It;s client side"

**Comment by CaiganMythFang** [comment]
Ending at Automation Station?

Could you start a single player world and see if it does likewise?

What is probably happening is the [RF Submission/Large Supply Order](https://github.com/CaiganMythFang/TheFerretBusinessIssues/issues/5) issue. Someone on the server is completing an RF Submission or Large Supply Order quest with the submission stations, which causes issues with the book in the current version.

**Comment by Haronobu** [comment]
that's what i meant by started new sp game. there are others on the server and i am the only 1 having this issue.

**Comment by CaiganMythFang** [comment]
Oh Whoops, I missed that.

That's very odd. Automation Station is the bottom of the quest list if you can't scroll (thus the RF Submission bug, which resets scrolling instantly). 

In single player, can you try doing /bq_admin edit, and then scrolling again? Or going into Designer(EDIT: In the quest tablet with edit mode on, hit Edit on the questline list to see the designer) and seeing if you can see the other questlines that way?

**Comment by Haronobu** [comment]
well i did /bq_admin edit in SP and now boy do i feel like a dope. it scrolled just fine but i have been trying to click on and move slider which DOESN'T work! So now i'm not even sure if i HAD a problem. thank you very much. and don't hesitate to have a laugh or 2 at my expense (I'm sure i will). thanks again and sorry to have bothered you(God do i feel stupid)

**Comment by CaiganMythFang** [comment]
Not a problem! Glad it was a simple issue. There's one or two scrollbars that don't work right it seems.
