### ISSUE TITLE
Cant start!

### ISSUE THREAD

**Issue by Mark0851** [CaiganMythFang/TheFerretBusinessIssues#91]
[crash-2020-03-30_14.13.35-client.txt](https://github.com/CaiganMythFang/TheFerretBusinessIssues/files/4402578/crash-2020-03-30_14.13.35-client.txt)

Help me there is something duplicated or i dont know.

**Comment by CaiganMythFang** [comment]
Hm I'm not sure what's causing this, other than it might be older update files still lingering for some reason after updating the pack. 

Try installing a completely new instance of the modpack on twitch and running it. If that works, move your saves over to the new install.
