### ISSUE TITLE
cannot break blocks

### ISSUE THREAD

**Issue by ghost** [CaiganMythFang/TheFerretBusinessIssues#93]
i am unable to break blocks using any tools.
if i use my hands im okay, but if i try to break any kind of blocks, with any kind of tools, it just won't work.

**Comment by CaiganMythFang** [comment]
This could be a couple issues :

Check that you aren't in Adventure mode (/gamemode s should put you back
into survival mode)

If that doesn't work, check if non vanilla tools work. (even a wooden
tinkers axe or something). If they do, it sounds like a Iguana Tinker
Tweaks option got changed somehow.

The configs for Iguana Tinker Tweaks has an option that disabled vanilla
tools from working.

**Comment by ghost** [comment]
ah yes it was disabled!
i have no idea how, i don't really touch files like that haha

thank you for the help!
